name: Gradle Publish

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Gradle
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: Publish package
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
      with:
        arguments: publish
      env:
        MAVEN_OSS_RELEASES_REPO_URL: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/
        MAVEN_OSS_SNAPSHOTS_REPO_URL: https://s01.oss.sonatype.org/content/repositories/snapshots/
        NEXUS_USER: ${{ secrets.OSS_SONATYPE_USERNAME }}
        NEXUS_PASS: ${{ secrets.OSS_SONATYPE_TOKEN }}

    - name: Publish to Gradle Portal
      run: ./gradlew -Dgradle.publish.key=$GRADLE_PUBLISH_KEY -Dgradle.publish.secret=$GRADLE_PUBLISH_SECRET publishPlugins
      env:
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
