name: Gradle Publish

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Gradle
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Retrieve the secret and decode it to a file
      run: |
        echo $SIGNING_KEY | base64 --decode > pgp_key
      env:
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

    - name: Build with Gradle
      run: ./gradlew -Psigning.secretKeyRingFile=pgp_key -Psigning.password=$SIGNING_PASS -Psigning.keyId=$SIGNING_KEY_ID build
      env:
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASS: ${{ secrets.SIGNING_PASS }}

    - name: Publish package
      run: ./gradlew -Psigning.secretKeyRingFile=pgp_key -Psigning.password=$SIGNING_PASS -Psigning.keyId=$SIGNING_KEY_ID publish
      env:
        MAVEN_OSS_RELEASES_REPO_URL: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/
        MAVEN_OSS_SNAPSHOTS_REPO_URL: https://s01.oss.sonatype.org/content/repositories/snapshots/
        NEXUS_USER: ${{ secrets.OSS_SONATYPE_USERNAME }}
        NEXUS_PASS: ${{ secrets.OSS_SONATYPE_TOKEN }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASS: ${{ secrets.SIGNING_PASS }}

    - name: Publish to Gradle Portal
      run: ./gradlew -Dgradle.publish.key=$GRADLE_PUBLISH_KEY -Dgradle.publish.secret=$GRADLE_PUBLISH_SECRET -Psigning.secretKeyRingFile=pgp_key -Psigning.password=$SIGNING_PASS -Psigning.keyId=$SIGNING_KEY_ID publishPlugins
      env:
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASS: ${{ secrets.SIGNING_PASS }}
